const products = [
  {name: "iPhone 17 Pro Max", brand: "apple", category: "phones", price: 1500, image: "imageA/i17PM.png"}, {name: "iPhone 17", brand: "apple", category: "phones", price: 1200, image: "imageA/I17.png"},{name: "iPhone 17e", brand: "apple", category: "phones", price: 1200, image: "imageA/I17e.png"}, {name: "iPhone 17 Pro", brand: "apple", category: "phones", price: 1200, image: "imageA/I17P.png"},{name: "iPhone 16", brand: "apple", category: "phones", price: 1200, image: "imageA/16.png"},{name: "iPhone 16e", brand: "apple", category: "phones", price: 1200, image: "imageA/I16e.png"}, {name: "iPhone 16 Plus", brand: "apple", category: "phones", price: 1200, image: "imageA/I16P.png"},{name: "iPhone 15 Pro", brand: "apple", category: "phones", price: 1200, image: "imageA/I15P.png"},{name: "iPhone 15", brand: "apple", category: "phones", price: 1200, image: "imageA/I15.png"},{name: "iPhone 14 Pro", brand: "apple", category: "phones", price: 1200, image: "imageA/I14P.png"}, {name: "iPhone 13", brand: "apple", category: "phones", price: 1200, image: "imageA/I13.png"},{name: "iPhone Air", brand: "apple", category: "phones", price: 900, image: "imageA/IA.png"},
  {name: "Samsung S25 FE", brand: "samsung", category: "phones", price: 600, image: "imageS/S25FE.png"},{name: "Samsung S23", brand: "samsung", category: "phones", price: 300, image: "imageS/SGS23.png"},{name: "Samsung A57", brand: "samsung", category: "phones", price: 500, image: "imageS/SA57.png"},{name: "Samsung A37", brand: "samsung", category: "phones", price:450, image: "imageS/A37.png"},{name: "Samsung S26 Ultra", brand: "samsung", category: "phones", price: 1050, image: "imageS/SGS26U.png"},{name: "Samsung S26 ", brand: "samsung", category: "phones", price: 800, image: "imageS/S26.png"},
  {name: "Xiaomi 13", brand: "xiaomi", category: "phones", price: 280, image: "imageX/X13.png"},{name: "Xiaomi Redmi 15C", brand: "xiaomi", category: "phones", price: 180, image: "imageX/XR15C.png"},{name: "Xiaomi Redmi Note 15", brand: "xiaomi", category: "phones", price: 150, image: "imageX/XR15.png"},{name: "Xiaomi Redmi Note 15 Pro", brand: "xiaomi", category: "phones", price: 240, image: "imageX/XR15P.png"},
  {name: "MacBook Pro 16", brand: "apple", category: "laptops", price: 2500, image: "imageA/MB16P.png"},{name: " Apple MacBook Neo 13 A18 Pro", brand: "apple", category: "laptops", price: 800, image: "imageA/MBN13.png"},
  {name: "Dell XPS 15", brand: "dell", category: "laptops", price: 900, image: "imageL/DXPS15.png"},
  {name: "ASUS TUF Gaming A15", brand: "asus", category: "laptops", price: 775, image: "imageL/ATuf.png"},
  {name: "ASUS TUF Gaming A16(2025)", brand: "asus", category: "laptops", price: 1000, image: "imageL/ATufA16.png"},
  {name: "ASUS ROG Strix G18 (2025)", brand: "asus", category: "laptops", price: 2000, image: "imageL/ARog.png"},
  {name: "USB-C Cable", brand: "generic", category: "accessories", price: 7, image: "image/C.png"},{name: "Xiaomi HyperCharge Combo 120W ", brand: "generic", category: "accessories", price: 15, image: "image/120W.png"},
  {name: "Apple AirPods 4 ", brand: "generic", category: "accessories", price: 170, image: "imageH/airpods4.png"},{name: "Apple AirPods Pro 3", brand: "generic", category: "accessories", price: 250, image: "imageH/airpodsp3.png"}, {name: "Apple AirPods Pro ", brand: "generic", category: "accessories", price: 100, image: "imageH/airpodsp.png"}, {name: "Marshall Major IV Bluetooth Headphones ", brand: "generic", category: "accessories", price: 55, image: "imageH/M.png"}
  
];

